/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectofinalbd1;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Snheider
 */
public class Administrador extends javax.swing.JFrame {
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();  
        
        MI_InsertarProductoActionPerformed(null);
    }

public void MostrarDatos(String nombre, String apellidos, int edad, String correo){

    L2.setText(nombre); L3.setText(apellidos); L4.setText(String.valueOf(edad)+" años"); 
    L5.setText(correo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        DP_Adminstrador = new javax.swing.JDesktopPane();
        L1 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        M_Archivo = new javax.swing.JMenu();
        MI_InsertarProducto = new javax.swing.JMenuItem();
        MI_ModificarProducto = new javax.swing.JMenuItem();
        MI_EliminarProducto = new javax.swing.JMenuItem();
        MI_InsertarUsuario = new javax.swing.JMenuItem();
        MI_ModificarUsuario = new javax.swing.JMenuItem();
        MI_EliminarUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MI_CerrarSesion = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMINISTRADOR");

        DP_Adminstrador.setPreferredSize(new java.awt.Dimension(700, 400));

        javax.swing.GroupLayout DP_AdminstradorLayout = new javax.swing.GroupLayout(DP_Adminstrador);
        DP_Adminstrador.setLayout(DP_AdminstradorLayout);
        DP_AdminstradorLayout.setHorizontalGroup(
            DP_AdminstradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        DP_AdminstradorLayout.setVerticalGroup(
            DP_AdminstradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        L1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        L1.setForeground(new java.awt.Color(255, 0, 0));
        L1.setText("ADMINSTRADOR:");

        L3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        L3.setText("1");

        L2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        L2.setText("1");

        L4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        L4.setText("1");

        L5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        L5.setText("1");

        M_Archivo.setText("Archivo");
        M_Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_ArchivoActionPerformed(evt);
            }
        });

        MI_InsertarProducto.setText("Insertar Producto");
        MI_InsertarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_InsertarProductoActionPerformed(evt);
            }
        });
        M_Archivo.add(MI_InsertarProducto);

        MI_ModificarProducto.setText("Modificar Producto");
        MI_ModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_ModificarProductoActionPerformed(evt);
            }
        });
        M_Archivo.add(MI_ModificarProducto);

        MI_EliminarProducto.setText("Eliminar Producto");
        MI_EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_EliminarProductoActionPerformed(evt);
            }
        });
        M_Archivo.add(MI_EliminarProducto);

        MI_InsertarUsuario.setText("Insertar Usuario");
        MI_InsertarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_InsertarUsuarioActionPerformed(evt);
            }
        });
        M_Archivo.add(MI_InsertarUsuario);

        MI_ModificarUsuario.setText("Modificar Usuario");
        MI_ModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_ModificarUsuarioActionPerformed(evt);
            }
        });
        M_Archivo.add(MI_ModificarUsuario);

        MI_EliminarUsuario.setText("Eliminar Usuario");
        MI_EliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_EliminarUsuarioActionPerformed(evt);
            }
        });
        M_Archivo.add(MI_EliminarUsuario);
        M_Archivo.add(jSeparator2);

        MI_CerrarSesion.setText("Cerrar Sesión");
        MI_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_CerrarSesionActionPerformed(evt);
            }
        });
        M_Archivo.add(MI_CerrarSesion);

        jMenuBar2.add(M_Archivo);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DP_Adminstrador, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(L4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(L5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L3, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(L2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(L4, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(L5, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(DP_Adminstrador, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void M_ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_ArchivoActionPerformed
        // TODO add your handling code here:
                
    }//GEN-LAST:event_M_ArchivoActionPerformed

    private void MI_InsertarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_InsertarProductoActionPerformed
        // TODO add your handling code here:
        AdministradorInsertarProducto ob = new AdministradorInsertarProducto();
        ob.setVisible(true);
        DP_Adminstrador.add(ob);
        
        try{
        ob.setMaximum(true);
        }
        catch(PropertyVetoException e){
        Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE,null,e);
        
        }
    }//GEN-LAST:event_MI_InsertarProductoActionPerformed

    private void MI_ModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_ModificarProductoActionPerformed
        // TODO add your handling code here:
         AdministradorModificarProducto ob = new AdministradorModificarProducto();
        ob.setVisible(true);
        DP_Adminstrador.add(ob);
        
        try{
        ob.setMaximum(true);
        }
        catch(PropertyVetoException e){
        Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE,null,e);
        
        }
    }//GEN-LAST:event_MI_ModificarProductoActionPerformed

    private void MI_EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_EliminarProductoActionPerformed
        // TODO add your handling code here:
        AdministradorEliminarProducto ob = new AdministradorEliminarProducto();
        ob.setVisible(true);
        DP_Adminstrador.add(ob);
        
        try{
        ob.setMaximum(true);
        }
        catch(PropertyVetoException e){
        Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE,null,e);
        
        }
    }//GEN-LAST:event_MI_EliminarProductoActionPerformed

    private void MI_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_CerrarSesionActionPerformed
        // TODO add your handling code here:
        
        Inicio mostrar = new Inicio();
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MI_CerrarSesionActionPerformed

    private void MI_InsertarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_InsertarUsuarioActionPerformed
        // TODO add your handling code here:
       AdministradorInsertarUsuario ob = new AdministradorInsertarUsuario();
       
        ob.setVisible(true);
        DP_Adminstrador.add(ob);
        DP_Adminstrador.setSize(900, 500);
        
        try{
        ob.setMaximum(true);
        }
        catch(PropertyVetoException e){
        Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE,null,e);
        
        }
        
    }//GEN-LAST:event_MI_InsertarUsuarioActionPerformed

    private void MI_ModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_ModificarUsuarioActionPerformed
        // TODO add your handling code here:
         AdministradorModificarUsuario ob = new AdministradorModificarUsuario();
       
        ob.setVisible(true);
        DP_Adminstrador.add(ob);
        DP_Adminstrador.setSize(900, 500);
        
        try{
        ob.setMaximum(true);
        }
        catch(PropertyVetoException e){
        Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE,null,e);
        
        }
    }//GEN-LAST:event_MI_ModificarUsuarioActionPerformed

    private void MI_EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_EliminarUsuarioActionPerformed
        // TODO add your handling code here:
         AdministradorEliminarUsuario ob = new AdministradorEliminarUsuario();
       
        ob.setVisible(true);
        DP_Adminstrador.add(ob);
        DP_Adminstrador.setSize(900, 500);
        
        try{
        ob.setMaximum(true);
        }
        catch(PropertyVetoException e){
        Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE,null,e);
        
        }
    }//GEN-LAST:event_MI_EliminarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DP_Adminstrador;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JMenuItem MI_CerrarSesion;
    private javax.swing.JMenuItem MI_EliminarProducto;
    private javax.swing.JMenuItem MI_EliminarUsuario;
    private javax.swing.JMenuItem MI_InsertarProducto;
    private javax.swing.JMenuItem MI_InsertarUsuario;
    private javax.swing.JMenuItem MI_ModificarProducto;
    private javax.swing.JMenuItem MI_ModificarUsuario;
    private javax.swing.JMenu M_Archivo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
