/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectofinalbd1;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Snheider
 */
public class AdministradorModificarUsuario extends javax.swing.JInternalFrame {
String Empty = new String(),datos[];
Connection cn;
Statement st;
ResultSet rs;
    /**
     * Creates new form AdministradorInsertarUsuario
     */
    public AdministradorModificarUsuario() {
        initComponents();
        MostrarUsuario();
        CB_TipoUsuario.addItem("");
        CB_TipoUsuario.addItem("ADMINISTRADOR");
        CB_TipoUsuario.addItem("CAJERO");
    }
    
     private void MostrarUsuario(){
        
    try {
        
        DefaultTableModel modelo=new DefaultTableModel();
        
            modelo.addColumn("Codigo");
            modelo.addColumn("Nombres");
            modelo.addColumn("Apellidos");
            modelo.addColumn("Edad");
            modelo.addColumn("correo");
            modelo.addColumn("Loggin");
            modelo.addColumn("Contraseña");
            modelo.addColumn("Rol");
          
          conexion ob = new conexion();
          cn=ob.con();
          st=cn.createStatement();
          rs=st.executeQuery("call SP_MostrarUsuario()");
         // System.out.println(rs);
          datos=new String[8];
          while(rs.next()){
          datos[0]=rs.getString(1);
          datos[1]=rs.getString(2);
          datos[2]=rs.getString(3);
          datos[3]=rs.getString(4);
          datos[4]=rs.getString(5);
          datos[5]=rs.getString(6);
          datos[6]=rs.getString(7);
          datos[7]=rs.getString(8);
          if(datos[7].equals("1"))
              datos[7]="ADMINISTRADOR";
          else
              datos[7]="CAJERO";
          
          modelo.addRow(datos);
          }
        
        T_Mostrar.setModel(modelo);
        
          cn.close();
          st.close();
          rs.close();
    } catch (SQLException ex) {
       // Logger.getLogger(AdministradorInsertarProducto.class.getName()).log(Level.SEVERE, null, ex);
         System.out.println("No se cargaron los datos, en el SP_MostrarProducto");
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        T_Mostrar = new javax.swing.JTable();
        B_BorrarCampos = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        TF_ApellidosUsuario = new javax.swing.JTextField();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        TF_EdadUsuario = new javax.swing.JTextField();
        Label4 = new javax.swing.JLabel();
        B_Modificar = new javax.swing.JButton();
        TF_NombresUsuario = new javax.swing.JTextField();
        Label5 = new javax.swing.JLabel();
        TF_CorreoUsuario = new javax.swing.JTextField();
        TF_LogginUsuario = new javax.swing.JTextField();
        Label6 = new javax.swing.JLabel();
        TF_PasswordUsuario = new javax.swing.JTextField();
        Label7 = new javax.swing.JLabel();
        CB_TipoUsuario = new javax.swing.JComboBox();
        Label8 = new javax.swing.JLabel();
        TF_CodigoUsuario = new javax.swing.JTextField();

        setTitle("Modificar Usuario");

        T_Mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(T_Mostrar);

        B_BorrarCampos.setText("BORRARCAMPOS");
        B_BorrarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BorrarCamposActionPerformed(evt);
            }
        });

        Label1.setText("Nombres:");

        TF_ApellidosUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_ApellidosUsuarioKeyTyped(evt);
            }
        });

        Label2.setText("Apellidos:");

        Label3.setText("Edad:");

        TF_EdadUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_EdadUsuarioKeyTyped(evt);
            }
        });

        Label4.setText("Loggin:");

        B_Modificar.setText("MODIFICAR");
        B_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ModificarActionPerformed(evt);
            }
        });

        TF_NombresUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_NombresUsuarioKeyTyped(evt);
            }
        });

        Label5.setText("Correo:");

        TF_CorreoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_CorreoUsuarioKeyTyped(evt);
            }
        });

        Label6.setText("Password:");

        Label7.setText("Rol del Usuario:");

        Label8.setText("Codigo:");

        TF_CodigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CodigoUsuarioActionPerformed(evt);
            }
        });
        TF_CodigoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TF_CodigoUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_CodigoUsuarioKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_Modificar)
                .addGap(84, 84, 84)
                .addComponent(B_BorrarCampos)
                .addGap(256, 256, 256))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TF_CodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_PasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_EdadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(501, 501, 501))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CB_TipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_CorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_NombresUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TF_ApellidosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(TF_LogginUsuario))
                                .addGap(77, 77, 77))))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label1)
                    .addComponent(TF_NombresUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label8)
                    .addComponent(TF_CodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label2)
                    .addComponent(TF_ApellidosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label5)
                    .addComponent(TF_CorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label3)
                    .addComponent(TF_EdadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label4)
                    .addComponent(TF_LogginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label6)
                    .addComponent(TF_PasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label7)
                    .addComponent(CB_TipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Modificar)
                    .addComponent(B_BorrarCampos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_BorrarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BorrarCamposActionPerformed
        // TODO add your handling code here:
        TF_CodigoUsuario.setText(Empty);
        TF_NombresUsuario.setText(Empty);
        TF_ApellidosUsuario.setText(Empty);
        TF_EdadUsuario.setText(Empty);
        TF_CorreoUsuario.setText(Empty);
        TF_LogginUsuario.setText(Empty);
        TF_CorreoUsuario.setText(Empty);
        TF_PasswordUsuario.setText(Empty);
        CB_TipoUsuario.setSelectedIndex(0);
        TF_CodigoUsuario.requestFocus();
    }//GEN-LAST:event_B_BorrarCamposActionPerformed

    private void TF_ApellidosUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_ApellidosUsuarioKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(Character.isDigit(c) || TF_ApellidosUsuario.getText().length()>20) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_TF_ApellidosUsuarioKeyTyped

    private void TF_EdadUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_EdadUsuarioKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(Character.isLetter(c) || TF_EdadUsuario.getText().length()>15) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_TF_EdadUsuarioKeyTyped

    private void B_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ModificarActionPerformed
        // TODO add your handling code here:
        int Rol=0;
        if(TF_NombresUsuario.getText().equals(Empty) || TF_ApellidosUsuario.getText().equals(Empty) ||
            TF_EdadUsuario.getText().equals(Empty) || TF_CorreoUsuario.getText().equals(Empty) || 
            TF_LogginUsuario.getText().equals(Empty) || TF_PasswordUsuario.getText().equals(Empty) || CB_TipoUsuario.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Campos vacios","¿?",JOptionPane.INFORMATION_MESSAGE);
        }else
        {
            try {
                if(CB_TipoUsuario.getSelectedIndex()==1)
                    Rol=1;
                else
                    if(CB_TipoUsuario.getSelectedIndex()==2)
                        Rol=2;
                
                conexion ob = new conexion();
                cn=ob.con();
                st=cn.createStatement();
                rs=st.executeQuery("call SP_ModificarUsuario("+Integer.parseInt(TF_CodigoUsuario.getText())+",'"
                    +TF_NombresUsuario.getText()+"','"+TF_ApellidosUsuario.getText()+"',"+Integer.parseInt(TF_EdadUsuario.getText())
                    +",'"+TF_CorreoUsuario.getText()+"','"+TF_LogginUsuario.getText()+"','"+TF_PasswordUsuario.getText()+"',"+Rol+")");
                   System.out.println(rs.toString());
                if(rs.toString().equals("Result set representing update count of 0")){
                JOptionPane.showMessageDialog(null,"Ese Codigo no existe","INCORRECTO!",JOptionPane.WARNING_MESSAGE);
                }else{

                   

                JOptionPane.showMessageDialog(null,"Se ha Modificado correctamente","CORRECTO!",JOptionPane.INFORMATION_MESSAGE);
                MostrarUsuario();
                }
                cn.close();
                st.close();
                rs.close();
            } catch (SQLException ex) {
                // Logger.getLogger(AdministradorInsertarProducto.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("No se cargaron los datos, en el SP_ModificarUsuario");
                }
             B_BorrarCamposActionPerformed(null);

        }
    }//GEN-LAST:event_B_ModificarActionPerformed

    private void TF_NombresUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_NombresUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_NombresUsuarioKeyTyped

    private void TF_CorreoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_CorreoUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_CorreoUsuarioKeyTyped

    private void TF_CodigoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_CodigoUsuarioKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TF_CodigoUsuarioKeyTyped

    private void TF_CodigoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_CodigoUsuarioKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_TF_CodigoUsuarioKeyPressed

    private void TF_CodigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CodigoUsuarioActionPerformed
        // TODO add your handling code here:
        
          try {
                
          conexion ob = new conexion();
          cn=ob.con();
          st=cn.createStatement();
          rs=st.executeQuery("call SP_MostrarUsuario()");
         // System.out.println(rs);
           
          while(rs.next()){
          if(TF_CodigoUsuario.getText().equals(rs.getString(1))){
          TF_NombresUsuario.setText(rs.getString(2));
          TF_ApellidosUsuario.setText(rs.getString(3));
          TF_EdadUsuario.setText(rs.getString(4));
          TF_CorreoUsuario.setText(rs.getString(5));
          TF_LogginUsuario.setText(rs.getString(6));
          TF_PasswordUsuario.setText(rs.getString(7));
          break;
          }else
          if(!TF_CodigoUsuario.getText().equals(rs.getString(1))){
       
        TF_NombresUsuario.setText(Empty);
        TF_ApellidosUsuario.setText(Empty);
        TF_EdadUsuario.setText(Empty);
        TF_CorreoUsuario.setText(Empty);
        TF_LogginUsuario.setText(Empty);
        TF_CorreoUsuario.setText(Empty);
        TF_PasswordUsuario.setText(Empty);
        CB_TipoUsuario.setSelectedIndex(0);
          }
          }
         
          cn.close();
          st.close();
          rs.close();
    } catch (SQLException ex) {
       // Logger.getLogger(AdministradorInsertarProducto.class.getName()).log(Level.SEVERE, null, ex);
         System.out.println("No se cargaron los datos, en el SP_MostrarProducto");
    }
    }//GEN-LAST:event_TF_CodigoUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_BorrarCampos;
    private javax.swing.JButton B_Modificar;
    private javax.swing.JComboBox CB_TipoUsuario;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JTextField TF_ApellidosUsuario;
    private javax.swing.JTextField TF_CodigoUsuario;
    private javax.swing.JTextField TF_CorreoUsuario;
    private javax.swing.JTextField TF_EdadUsuario;
    private javax.swing.JTextField TF_LogginUsuario;
    private javax.swing.JTextField TF_NombresUsuario;
    private javax.swing.JTextField TF_PasswordUsuario;
    private javax.swing.JTable T_Mostrar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
