/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectofinalbd1;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Snheider
 */
public class AdministradorEliminarProducto extends javax.swing.JInternalFrame {
String Empty = new String(),datos[]; 
Connection cn;
Statement st;
ResultSet rs;
int i,j,k,l;
    /**
     * Creates new form AdministradorEliminarProducto
     */
    public AdministradorEliminarProducto() {
        initComponents();
        MostrarProducto();
    }

     private void MostrarProducto(){
        
    try {
        
        DefaultTableModel modelo=new DefaultTableModel();
        
            modelo.addColumn("CodigoProducto");
            modelo.addColumn("NombreProducto");
            modelo.addColumn("PrecioProducto");
            modelo.addColumn("NombreImagen");
          
          conexion ob = new conexion();
          cn=ob.con();
          st=cn.createStatement();
          rs=st.executeQuery("call SP_MostrarProducto()");
         // System.out.println(rs);
          datos=new String[4];
          while(rs.next()){
          datos[0]=rs.getString(1);
          datos[1]=rs.getString(2);
          datos[2]=rs.getString(3);
          datos[3]=rs.getString(4);
          modelo.addRow(datos);
          }
         
        
        T_Mostrar.setModel(modelo);
        
          cn.close();
          st.close();
          rs.close();
    } catch (SQLException ex) {
       // Logger.getLogger(AdministradorInsertarProducto.class.getName()).log(Level.SEVERE, null, ex);
         System.out.println("No se cargaron los datos, en el SP_MostrarProducto");
    }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        T_Mostrar = new javax.swing.JTable();
        TF_CodigoProducto = new javax.swing.JTextField();
        B_BorrarCampos = new javax.swing.JButton();
        B_Eliminar = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();

        setTitle("Eliminar Producto");

        T_Mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(T_Mostrar);

        TF_CodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_CodigoProductoKeyTyped(evt);
            }
        });

        B_BorrarCampos.setText("BORRARCAMPOS");
        B_BorrarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BorrarCamposActionPerformed(evt);
            }
        });

        B_Eliminar.setText("ELIMINAR");
        B_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EliminarActionPerformed(evt);
            }
        });

        Label1.setText("Codigo del Producto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_CodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(B_Eliminar)
                        .addGap(67, 67, 67)))
                .addGap(17, 17, 17)
                .addComponent(B_BorrarCampos)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label1)
                    .addComponent(TF_CodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Eliminar)
                    .addComponent(B_BorrarCampos))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_CodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_CodigoProductoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(Character.isLetter(c) || TF_CodigoProducto.getText().length()>10) {
            getToolkit().beep();

            evt.consume();
        }

    }//GEN-LAST:event_TF_CodigoProductoKeyTyped

    private void B_BorrarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BorrarCamposActionPerformed
        // TODO add your handling code here:
        TF_CodigoProducto.setText(Empty);
        TF_CodigoProducto.requestFocus();
    }//GEN-LAST:event_B_BorrarCamposActionPerformed

    private void B_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EliminarActionPerformed
        // TODO add your handling code here:
        if(TF_CodigoProducto.getText().equals(Empty)){
            JOptionPane.showMessageDialog(null,"Campos vacios","¿?",JOptionPane.INFORMATION_MESSAGE);
        }else
        {
            try {

                conexion ob = new conexion();
                cn=ob.con();
                st=cn.createStatement();
                rs=st.executeQuery("call SP_EliminarProducto("+Integer.parseInt(TF_CodigoProducto.getText())+")");

                System.out.println(rs.toString());
                if(rs.toString().equals("Result set representing update count of 0")){
                    JOptionPane.showMessageDialog(null,"Ese Codigo no existe","INCORRECTO!",JOptionPane.WARNING_MESSAGE);
                }else{
                    TF_CodigoProducto.setText(Empty);
                    TF_CodigoProducto.requestFocus();

                    JOptionPane.showMessageDialog(null,"Se ha Eliminado correctamente","CORRECTO!",JOptionPane.INFORMATION_MESSAGE);
                    MostrarProducto();
                }
                cn.close();
                st.close();
                rs.close();
            } catch (SQLException ex) {
                // Logger.getLogger(AdministradorInsertarProducto.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("No se cargaron los datos, en el SP_EliminarProducto");
            }

        }
    }//GEN-LAST:event_B_EliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_BorrarCampos;
    private javax.swing.JButton B_Eliminar;
    private javax.swing.JLabel Label1;
    private javax.swing.JTextField TF_CodigoProducto;
    private javax.swing.JTable T_Mostrar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
