/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectofinalbd1;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Snheider
 */
public class AdministradorModificarProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdministradorModificarProducto
     */
String Empty = new String(),datos[]; 
Connection cn;
Statement st;
ResultSet rs;
int i,j,k,l;
    public AdministradorModificarProducto() {
        initComponents();
        TF_Examinar.enable(false);
        MostrarProducto();
    }
    
        private void MostrarProducto(){
        
    try {
        
        DefaultTableModel modelo=new DefaultTableModel();
        
            modelo.addColumn("CodigoProducto");
            modelo.addColumn("NombreProducto");
            modelo.addColumn("PrecioProducto");
            modelo.addColumn("NombreImagen");
          
          conexion ob = new conexion();
          cn=ob.con();
          st=cn.createStatement();
          rs=st.executeQuery("call SP_MostrarProducto()");
         // System.out.println(rs);
          datos=new String[4];
          while(rs.next()){
          datos[0]=rs.getString(1);
          datos[1]=rs.getString(2);
          datos[2]=rs.getString(3);
          datos[3]=rs.getString(4);
          modelo.addRow(datos);
          }
         
        
        T_Mostrar.setModel(modelo);
        
          cn.close();
          st.close();
          rs.close();
    } catch (SQLException ex) {
       // Logger.getLogger(AdministradorInsertarProducto.class.getName()).log(Level.SEVERE, null, ex);
         System.out.println("No se cargaron los datos, en el SP_MostrarProducto");
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label1 = new javax.swing.JLabel();
        TF_NombreProducto = new javax.swing.JTextField();
        Label2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_Mostrar = new javax.swing.JTable();
        TF_CodigoProducto = new javax.swing.JTextField();
        Label3 = new javax.swing.JLabel();
        TF_PrecioProducto = new javax.swing.JTextField();
        Label4 = new javax.swing.JLabel();
        B_BorrarCampos = new javax.swing.JButton();
        B_Modificar = new javax.swing.JButton();
        TF_Examinar = new javax.swing.JTextField();
        B_Examinar = new javax.swing.JButton();

        setTitle("ModificarProducto");

        Label1.setText("Codigo del Producto:");

        TF_NombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_NombreProductoKeyTyped(evt);
            }
        });

        Label2.setText("Nombre del Producto:");

        T_Mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(T_Mostrar);

        TF_CodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CodigoProductoActionPerformed(evt);
            }
        });
        TF_CodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_CodigoProductoKeyTyped(evt);
            }
        });

        Label3.setText("Precio del Producto:");

        TF_PrecioProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_PrecioProductoKeyTyped(evt);
            }
        });

        Label4.setText("Imagen del Producto:");

        B_BorrarCampos.setText("BORRARCAMPOS");
        B_BorrarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BorrarCamposActionPerformed(evt);
            }
        });

        B_Modificar.setText("MODIFICAR");
        B_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ModificarActionPerformed(evt);
            }
        });

        TF_Examinar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_ExaminarKeyTyped(evt);
            }
        });

        B_Examinar.setText("EXAMINAR");
        B_Examinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ExaminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Label3, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_CodigoProducto)
                            .addComponent(TF_PrecioProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(B_Modificar)
                        .addGap(67, 67, 67)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(B_BorrarCampos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Label4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TF_Examinar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_Examinar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TF_CodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label2)
                        .addComponent(TF_NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TF_Examinar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_Examinar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label4)
                        .addComponent(Label3)
                        .addComponent(TF_PrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Modificar)
                    .addComponent(B_BorrarCampos))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_NombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_NombreProductoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(Character.isDigit(c) || TF_NombreProducto.getText().length()>20) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_TF_NombreProductoKeyTyped

    private void TF_CodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_CodigoProductoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(Character.isLetter(c) || TF_CodigoProducto.getText().length()>10) {
            getToolkit().beep();

            evt.consume();
        }
                 
    }//GEN-LAST:event_TF_CodigoProductoKeyTyped

    private void TF_PrecioProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_PrecioProductoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(Character.isLetter(c) || TF_PrecioProducto.getText().length()>15) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_TF_PrecioProductoKeyTyped

    private void B_BorrarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BorrarCamposActionPerformed
        // TODO add your handling code here:
        TF_CodigoProducto.setText(Empty);
        TF_NombreProducto.setText(Empty);
        TF_PrecioProducto.setText(Empty);
        TF_Examinar.setText(Empty);
        TF_CodigoProducto.requestFocus();
    }//GEN-LAST:event_B_BorrarCamposActionPerformed

    private void B_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ModificarActionPerformed
        // TODO add your handling code here:
        if(TF_CodigoProducto.getText().equals(Empty) || TF_NombreProducto.getText().equals(Empty) ||
            TF_PrecioProducto.getText().equals(Empty) || TF_Examinar.getText().equals(Empty)){
            JOptionPane.showMessageDialog(null,"Campos vacios","¿?",JOptionPane.INFORMATION_MESSAGE);
        }else
        {
            try {
                
                conexion ob = new conexion();
                cn=ob.con();
                st=cn.createStatement();
                rs=st.executeQuery("call SP_ModificarProducto("+Integer.parseInt(TF_CodigoProducto.getText())+",'"
                    +TF_NombreProducto.getText()+"',"+Double.parseDouble(TF_PrecioProducto.getText())+",'"+TF_Examinar.getText()+"')");
               
                System.out.println(rs.toString());
                if(rs.toString().equals("Result set representing update count of 0")){
                JOptionPane.showMessageDialog(null,"Ese Codigo no existe","INCORRECTO!",JOptionPane.WARNING_MESSAGE);
                }else{
                TF_CodigoProducto.setText(Empty);
                TF_NombreProducto.setText(Empty);
                TF_PrecioProducto.setText(Empty);
                TF_Examinar.setText(Empty);
                TF_CodigoProducto.requestFocus();
                
                JOptionPane.showMessageDialog(null,"Se ha Modificado correctamente","CORRECTO!",JOptionPane.INFORMATION_MESSAGE);
                MostrarProducto();
                }
                 cn.close();
                 st.close();
                 rs.close();
            } catch (SQLException ex) {
                // Logger.getLogger(AdministradorInsertarProducto.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("No se cargaron los datos, en el SP_ModificarProducto");
            }

        }
    }//GEN-LAST:event_B_ModificarActionPerformed

    private void TF_ExaminarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_ExaminarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_ExaminarKeyTyped

    private void B_ExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ExaminarActionPerformed
        // TODO add your handling code here:

        final JFrame vn = new JFrame("Abrir");
        vn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        final JFileChooser FC_Examinar = new JFileChooser();

        FC_Examinar.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                String command=ae.getActionCommand();
                if(command.equals(JFileChooser.APPROVE_SELECTION)){
                    File archivoSeleccionado =FC_Examinar.getSelectedFile();
                    TF_Examinar.setText(archivoSeleccionado.getName());
                    vn.dispose();
                }else
                if(command.equals(JFileChooser.CANCEL_SELECTION)){
                    vn.dispose();
                }
            }
        });
        vn.add(FC_Examinar,BorderLayout.CENTER);
        vn.pack();
        vn.setVisible(true);
    }//GEN-LAST:event_B_ExaminarActionPerformed

    private void TF_CodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CodigoProductoActionPerformed
        // TODO add your handling code here:
         try {
                
          conexion ob = new conexion();
          cn=ob.con();
          st=cn.createStatement();
          rs=st.executeQuery("call SP_MostrarProducto()");
         // System.out.println(rs);
           
          while(rs.next()){
          if(TF_CodigoProducto.getText().equals(rs.getString(1))){
             TF_NombreProducto.setText(rs.getString(2));
             TF_PrecioProducto.setText(rs.getString(3));
             TF_Examinar.setText(rs.getString(4));
          break;
          }else
          if(!TF_CodigoProducto.getText().equals(rs.getString(1))){
       
        TF_NombreProducto.setText(Empty);
        TF_PrecioProducto.setText(Empty);
        TF_Examinar.setText(Empty);
        
          }
          }
         
          cn.close();
          st.close();
          rs.close();
    } catch (SQLException ex) {
       // Logger.getLogger(AdministradorInsertarProducto.class.getName()).log(Level.SEVERE, null, ex);
         System.out.println("No se cargaron los datos, en el SP_MostrarProducto");
    }
    }//GEN-LAST:event_TF_CodigoProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_BorrarCampos;
    private javax.swing.JButton B_Examinar;
    private javax.swing.JButton B_Modificar;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JTextField TF_CodigoProducto;
    private javax.swing.JTextField TF_Examinar;
    private javax.swing.JTextField TF_NombreProducto;
    private javax.swing.JTextField TF_PrecioProducto;
    private javax.swing.JTable T_Mostrar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
