/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectofinalbd1;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Snheider
 */
public class AdministradorEliminarUsuario extends javax.swing.JInternalFrame {
String Empty = new String(),datos[];
Connection cn;
Statement st;
ResultSet rs;
    /**
     * Creates new form AdministradorInsertarUsuario
     */
    public AdministradorEliminarUsuario() {
        initComponents();
        MostrarUsuario();
        
    }
    
     private void MostrarUsuario(){
        
    try {
        
        DefaultTableModel modelo=new DefaultTableModel();
        
            modelo.addColumn("Codigo");
            modelo.addColumn("Nombres");
            modelo.addColumn("Apellidos");
            modelo.addColumn("Edad");
            modelo.addColumn("correo");
            modelo.addColumn("Loggin");
            modelo.addColumn("Contraseña");
            modelo.addColumn("Rol");
          
          conexion ob = new conexion();
          cn=ob.con();
          st=cn.createStatement();
          rs=st.executeQuery("call SP_MostrarUsuario()");
         // System.out.println(rs);
          datos=new String[8];
          while(rs.next()){
          datos[0]=rs.getString(1);
          datos[1]=rs.getString(2);
          datos[2]=rs.getString(3);
          datos[3]=rs.getString(4);
          datos[4]=rs.getString(5);
          datos[5]=rs.getString(6);
          datos[6]=rs.getString(7);
          datos[7]=rs.getString(8);
          if(datos[7].equals("1"))
              datos[7]="ADMINISTRADOR";
          else
              datos[7]="CAJERO";
          
          modelo.addRow(datos);
          }
        
        T_Mostrar.setModel(modelo);
        
          cn.close();
          st.close();
          rs.close();
    } catch (SQLException ex) {
       // Logger.getLogger(AdministradorInsertarProducto.class.getName()).log(Level.SEVERE, null, ex);
         System.out.println("No se cargaron los datos, en el SP_MostrarProducto");
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        T_Mostrar = new javax.swing.JTable();
        B_BorrarCampos = new javax.swing.JButton();
        B_Eliminar = new javax.swing.JButton();
        Label8 = new javax.swing.JLabel();
        TF_CodigoUsuario = new javax.swing.JTextField();

        setTitle("Eliminar Usuario");

        T_Mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(T_Mostrar);

        B_BorrarCampos.setText("BORRARCAMPOS");
        B_BorrarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BorrarCamposActionPerformed(evt);
            }
        });

        B_Eliminar.setText("ELIMINAR");
        B_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EliminarActionPerformed(evt);
            }
        });

        Label8.setText("Codigo:");

        TF_CodigoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_CodigoUsuarioKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Label8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TF_CodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(B_Eliminar)
                        .addGap(84, 84, 84)
                        .addComponent(B_BorrarCampos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label8)
                    .addComponent(TF_CodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Eliminar)
                    .addComponent(B_BorrarCampos))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_BorrarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BorrarCamposActionPerformed
        // TODO add your handling code here:
         TF_CodigoUsuario.setText(Empty);
        TF_CodigoUsuario.requestFocus();
    }//GEN-LAST:event_B_BorrarCamposActionPerformed

    private void B_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EliminarActionPerformed
        // TODO add your handling code here:
        int Rol=0;
        if(TF_CodigoUsuario.getText().equals(Empty)){
            JOptionPane.showMessageDialog(null,"Campos vacios","¿?",JOptionPane.INFORMATION_MESSAGE);
        }else
        {
            try {
                                
                conexion ob = new conexion();
                cn=ob.con();
                st=cn.createStatement();
                rs=st.executeQuery("call SP_EliminarUsuario("+Integer.parseInt(TF_CodigoUsuario.getText())+")");
        System.out.println(rs.toString());
                if(rs.toString().equals("Result set representing update count of 0")){
                JOptionPane.showMessageDialog(null,"Ese Codigo no existe","INCORRECTO!",JOptionPane.WARNING_MESSAGE);
                }else{

        TF_CodigoUsuario.setText(Empty);
        TF_CodigoUsuario.requestFocus();

                JOptionPane.showMessageDialog(null,"Se ha Eliminado correctamente","CORRECTO!",JOptionPane.INFORMATION_MESSAGE);
                MostrarUsuario();
                }
                cn.close();
                st.close();
                rs.close();
            } catch (SQLException ex) {
                // Logger.getLogger(AdministradorInsertarProducto.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("No se cargaron los datos, en el SP_ModificarUsuario");
                }

        }
    }//GEN-LAST:event_B_EliminarActionPerformed

    private void TF_CodigoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_CodigoUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_CodigoUsuarioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_BorrarCampos;
    private javax.swing.JButton B_Eliminar;
    private javax.swing.JLabel Label8;
    private javax.swing.JTextField TF_CodigoUsuario;
    private javax.swing.JTable T_Mostrar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
