/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectofinalbd1;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Snheider
 */
public class Cajero extends javax.swing.JFrame {

    /**
     * Creates new form Cajero
     */
    public Cajero() {
        initComponents();
        MI_InsertarPedidoActionPerformed(null);
    }
  
  public void MostrarDatos(String nombre, String apellidos, int edad, String correo){

    L2.setText(nombre); L3.setText(apellidos); L4.setText(String.valueOf(edad)+" años"); 
    L5.setText(correo);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L1 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        DP_Cajero = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        M_Archivo = new javax.swing.JMenu();
        MI_InsertarPedido = new javax.swing.JMenuItem();
        MI_ModificarPedido = new javax.swing.JMenuItem();
        MI_EliminarPedido = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MI_CerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAJERO");

        L1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        L1.setForeground(new java.awt.Color(255, 0, 0));
        L1.setText("CAJERO:");

        L3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        L3.setText("1");

        L2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        L2.setText("1");

        L4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        L4.setText("1");

        L5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        L5.setText("1");

        DP_Cajero.setPreferredSize(new java.awt.Dimension(700, 400));

        javax.swing.GroupLayout DP_CajeroLayout = new javax.swing.GroupLayout(DP_Cajero);
        DP_Cajero.setLayout(DP_CajeroLayout);
        DP_CajeroLayout.setHorizontalGroup(
            DP_CajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );
        DP_CajeroLayout.setVerticalGroup(
            DP_CajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        M_Archivo.setText("Archivo");
        M_Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_ArchivoActionPerformed(evt);
            }
        });

        MI_InsertarPedido.setText("Insertar Pedido");
        MI_InsertarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_InsertarPedidoActionPerformed(evt);
            }
        });
        M_Archivo.add(MI_InsertarPedido);

        MI_ModificarPedido.setText("Modificar Pedido");
        MI_ModificarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_ModificarPedidoActionPerformed(evt);
            }
        });
        M_Archivo.add(MI_ModificarPedido);

        MI_EliminarPedido.setText("Eliminar Pedido");
        MI_EliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_EliminarPedidoActionPerformed(evt);
            }
        });
        M_Archivo.add(MI_EliminarPedido);
        M_Archivo.add(jSeparator2);

        MI_CerrarSesion.setText("Cerrar Sesión");
        MI_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_CerrarSesionActionPerformed(evt);
            }
        });
        M_Archivo.add(MI_CerrarSesion);

        jMenuBar2.add(M_Archivo);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DP_Cajero, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(L4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(L5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L3, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(L2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(L4, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(L5, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(DP_Cajero, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MI_InsertarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_InsertarPedidoActionPerformed
        // TODO add your handling code here:
        CajeroInsertarPedido ob = new CajeroInsertarPedido();
        ob.setVisible(true);
        DP_Cajero.add(ob);

        try{
            ob.setMaximum(true);
        }
        catch(PropertyVetoException e){
            Logger.getLogger(Cajero.class.getName()).log(Level.SEVERE,null,e);

        }
    }//GEN-LAST:event_MI_InsertarPedidoActionPerformed

    private void MI_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_CerrarSesionActionPerformed
        // TODO add your handling code here:

        Inicio mostrar = new Inicio();
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MI_CerrarSesionActionPerformed

    private void M_ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_ArchivoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_M_ArchivoActionPerformed

    private void MI_ModificarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_ModificarPedidoActionPerformed
        // TODO add your handling code here:
        CajeroModificarPedido ob = new CajeroModificarPedido();
        ob.setVisible(true);
        DP_Cajero.add(ob);

        try{
            ob.setMaximum(true);
        }
        catch(PropertyVetoException e){
            Logger.getLogger(Cajero.class.getName()).log(Level.SEVERE,null,e);

        }
    }//GEN-LAST:event_MI_ModificarPedidoActionPerformed

    private void MI_EliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_EliminarPedidoActionPerformed
        // TODO add your handling code here:
        
        CajeroEliminarPedido ob = new CajeroEliminarPedido();
        ob.setVisible(true);
        DP_Cajero.add(ob);

        try{
            ob.setMaximum(true);
        }
        catch(PropertyVetoException e){
            Logger.getLogger(Cajero.class.getName()).log(Level.SEVERE,null,e);

        }
    }//GEN-LAST:event_MI_EliminarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DP_Cajero;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JMenuItem MI_CerrarSesion;
    private javax.swing.JMenuItem MI_EliminarPedido;
    private javax.swing.JMenuItem MI_InsertarPedido;
    private javax.swing.JMenuItem MI_ModificarPedido;
    private javax.swing.JMenu M_Archivo;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
