/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectofinalbd1;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Snheider
 */
public class CajeroModificarPedido extends javax.swing.JInternalFrame {

File myDir = new File(".");
String myDirStr = "";
    
String Empty = new String(),datos[],CB_String;
String Ruta="";
Connection cn;
Statement st;
ResultSet rs;
ImageIcon foto;
 Icon icono;
int i,j,k,l;
    /**
     * Creates new form CajeroInsertarPedido
     */
    public CajeroModificarPedido() {
        try {
            myDirStr = myDir.getCanonicalPath(); ///Guarda la ruta del equipo
            System.out.printf(myDirStr);
            Ruta = myDirStr + "/imagenes/";
        } catch (IOException ex) {
            Logger.getLogger(CajeroModificarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        MostrarCarrito();
    }

     private void MostrarCarrito(){
         
         double total=0; 
    try {
        
        DefaultTableModel modelo=new DefaultTableModel();
        
            modelo.addColumn("idCarrito");
            modelo.addColumn("Nombre del Producto");
            modelo.addColumn("Cantidad del Producto");
            modelo.addColumn("Precio (C/U)");
            modelo.addColumn("Precio Total");
                      
          conexion ob = new conexion();
          cn=ob.con();
          st=cn.createStatement();
          rs=st.executeQuery("call SP_MostrarCarrito()");
         // System.out.println(rs);
          datos=new String[5];
          while(rs.next()){
          datos[0]=rs.getString(1);
          datos[1]=rs.getString(2);
          datos[2]=rs.getString(3);
          datos[3]=rs.getString(4);
          datos[4]=rs.getString(5);
          total+=Double.parseDouble(datos[4]);
          modelo.addRow(datos);
          }
          datos[0]="";
          datos[1]="";
          datos[2]="";
          datos[3]="";
          datos[4]="";
          modelo.addRow(datos);
          datos[0]="Total ";
          datos[1]="";
          datos[2]="";
          datos[3]="";
          datos[4]=String.valueOf(total);
          modelo.addRow(datos);
          T_Mostrar.setModel(modelo);
        
          cn.close();
          st.close();
          rs.close();
    } catch (SQLException ex) {
       // Logger.getLogger(AdministradorInsertarProducto.class.getName()).log(Level.SEVERE, null, ex);
         System.out.println("No se cargaron los datos, en el SP_MostrarProducto");
    }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        TF_CantidadProducto = new javax.swing.JTextField();
        B_ModificarPedido = new javax.swing.JButton();
        B_BorrarCampos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_Mostrar = new javax.swing.JTable();
        L3 = new javax.swing.JLabel();
        L_Inicio = new javax.swing.JLabel();
        TF_IdCarrito = new javax.swing.JTextField();
        L4 = new javax.swing.JLabel();
        B_GenerarRecibo = new javax.swing.JButton();
        B_VaciarCarrito = new javax.swing.JButton();

        setTitle("ModificarPedido");

        L1.setText("Id Carrito:");

        L2.setText("Cantidad del Producto:");

        TF_CantidadProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_CantidadProductoKeyTyped(evt);
            }
        });

        B_ModificarPedido.setText("MODIFICAR");
        B_ModificarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ModificarPedidoActionPerformed(evt);
            }
        });

        B_BorrarCampos.setText("BORRARCAMPOS");
        B_BorrarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BorrarCamposActionPerformed(evt);
            }
        });

        T_Mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(T_Mostrar);

        L3.setText("Imagen");

        L_Inicio.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        L_Inicio.setForeground(new java.awt.Color(255, 0, 0));
        L_Inicio.setText("CARRITO DE COMPRAS");

        TF_IdCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_IdCarritoActionPerformed(evt);
            }
        });
        TF_IdCarrito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_IdCarritoKeyTyped(evt);
            }
        });

        L4.setText("1");

        B_GenerarRecibo.setText("RECIBO");
        B_GenerarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_GenerarReciboActionPerformed(evt);
            }
        });

        B_VaciarCarrito.setText("VACIAR CARRITO");
        B_VaciarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_VaciarCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TF_IdCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(193, 193, 193)
                                        .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TF_CantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(135, 135, 135)
                                        .addComponent(L_Inicio))
                                    .addComponent(L4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(B_ModificarPedido)
                                .addGap(18, 18, 18)
                                .addComponent(B_BorrarCampos)
                                .addGap(18, 18, 18)
                                .addComponent(B_GenerarRecibo)
                                .addGap(31, 31, 31)
                                .addComponent(B_VaciarCarrito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L1)
                    .addComponent(L2)
                    .addComponent(TF_CantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_IdCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_ModificarPedido)
                            .addComponent(B_BorrarCampos)
                            .addComponent(B_GenerarRecibo)
                            .addComponent(B_VaciarCarrito))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(L_Inicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_CantidadProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_CantidadProductoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(Character.isLetter(c) || TF_CantidadProducto.getText().length()>15) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_TF_CantidadProductoKeyTyped

    private void B_ModificarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ModificarPedidoActionPerformed
        // TODO add your handling code here:
        if(TF_IdCarrito.getText().equals(Empty) || TF_CantidadProducto.getText().equals(Empty)){
            JOptionPane.showMessageDialog(null,"Campos vacios","¿?",JOptionPane.INFORMATION_MESSAGE);
        }else
        {
            try {
                
                conexion ob = new conexion();
                cn=ob.con();
                st=cn.createStatement();
                rs=st.executeQuery("call SP_ModificarCarrito("+Integer.parseInt(TF_IdCarrito.getText())+
                        ","+Integer.parseInt(TF_CantidadProducto.getText())+")");
               
                System.out.println(rs.toString());
                if(rs.toString().equals("Result set representing update count of 0")){
                JOptionPane.showMessageDialog(null,"Ese Codigo no existe","INCORRECTO!",JOptionPane.WARNING_MESSAGE);
                }else{
                    TF_IdCarrito.setText(Empty);
                 TF_CantidadProducto.setText(Empty);
                    L4.setText(Empty);
                    L3.setIcon(null);
                
                JOptionPane.showMessageDialog(null,"Se ha Modificado correctamente","CORRECTO!",JOptionPane.INFORMATION_MESSAGE);
                MostrarCarrito();
                }
                 cn.close();
                 st.close();
                 rs.close();
            } catch (SQLException ex) {
                // Logger.getLogger(AdministradorInsertarProducto.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("No se cargaron los datos, en el SP_ModificarCarrito");
            }
        }
    }//GEN-LAST:event_B_ModificarPedidoActionPerformed

    private void B_BorrarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BorrarCamposActionPerformed
        // TODO add your handling code here:
        TF_IdCarrito.setText(Empty);
        TF_CantidadProducto.setText(Empty);
    }//GEN-LAST:event_B_BorrarCamposActionPerformed

    private void TF_IdCarritoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_IdCarritoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_IdCarritoKeyTyped

    private void TF_IdCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_IdCarritoActionPerformed
        // TODO add your handling code here:

        try {

            conexion ob = new conexion();
            cn=ob.con();
            st=cn.createStatement();
            rs=st.executeQuery("call SP_MostrarCarrito()");
            // System.out.println(rs);

            while(rs.next()){
                if(TF_IdCarrito.getText().equals(rs.getString(1))){
                    TF_CantidadProducto.setText(rs.getString(3));
                    L4.setText(rs.getString(2));
                    foto = new ImageIcon(Ruta+rs.getString(6));
                    L3.setIcon(new ImageIcon(foto.getImage().getScaledInstance(100,100,Image.SCALE_SMOOTH)));
                    break;
                }else
                if(!TF_IdCarrito.getText().equals(rs.getString(1))){

                    TF_CantidadProducto.setText(Empty);
                    L4.setText(Empty);
                    L3.setIcon(null);

                }
            }

            cn.close();
            st.close();
            rs.close();
        } catch (SQLException ex) {
            // Logger.getLogger(AdministradorInsertarProducto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("No se cargaron los datos, en el SP_MostrarProducto");
        }
    }//GEN-LAST:event_TF_IdCarritoActionPerformed

    private void B_GenerarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_GenerarReciboActionPerformed
        // TODO add your handling code here:
        String RutaJasperReport=myDirStr+"/Reporte/report.jasper";
         conexion ob = new conexion();
         cn = ob.con();
        JasperPrint informe;
    try {
        informe = JasperFillManager.fillReport(RutaJasperReport,null, cn);
        JasperViewer ventanavisor = new JasperViewer(informe,false);
        ventanavisor.setTitle("INFORME");
        ventanavisor.setVisible(true);
    } catch (JRException ex) {
        Logger.getLogger(CajeroInsertarPedido.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_B_GenerarReciboActionPerformed

    private void B_VaciarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_VaciarCarritoActionPerformed
        // TODO add your handling code here:

         
        conexion ob = new conexion();
          cn=ob.con();
    try {
        st=cn.createStatement();
        st.executeQuery("call SP_VaciarCarrito()");
    } catch (SQLException ex) {
        Logger.getLogger(CajeroEliminarPedido.class.getName()).log(Level.SEVERE, null, ex);
    }
         MostrarCarrito();
    }//GEN-LAST:event_B_VaciarCarritoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_BorrarCampos;
    private javax.swing.JButton B_GenerarRecibo;
    private javax.swing.JButton B_ModificarPedido;
    private javax.swing.JButton B_VaciarCarrito;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L_Inicio;
    private javax.swing.JTextField TF_CantidadProducto;
    private javax.swing.JTextField TF_IdCarrito;
    private javax.swing.JTable T_Mostrar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
