/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectofinalbd1;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Snheider
 */


public class Inicio extends javax.swing.JFrame {
    /**
     * Creates new form Inicio
     */
    
String Empty = new String(); 
Connection cn;
Statement st;
ResultSet rs;
int i,j,k,l;

    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_Inicio = new javax.swing.JLabel();
        L_Nombre = new javax.swing.JLabel();
        L_Contraseña = new javax.swing.JLabel();
        B_limpiar = new javax.swing.JButton();
        B_Aceptar = new javax.swing.JButton();
        B_Salir = new javax.swing.JButton();
        TF_Usuario = new javax.swing.JTextField();
        PF_Contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PAGINA DE INICIO");

        L_Inicio.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        L_Inicio.setForeground(new java.awt.Color(255, 0, 0));
        L_Inicio.setText("BIENVENIDO A LA TIENDA");

        L_Nombre.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        L_Nombre.setText("USUARIO :");

        L_Contraseña.setFont(L_Nombre.getFont());
        L_Contraseña.setText("CONTRASEÑA:");

        B_limpiar.setFont(L_Nombre.getFont());
        B_limpiar.setText("Limpiar");
        B_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_limpiarActionPerformed(evt);
            }
        });

        B_Aceptar.setFont(L_Nombre.getFont());
        B_Aceptar.setText("Aceptar");
        B_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AceptarActionPerformed(evt);
            }
        });

        B_Salir.setFont(L_Nombre.getFont());
        B_Salir.setText("Salir");
        B_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SalirActionPerformed(evt);
            }
        });

        TF_Usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(L_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PF_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_Aceptar)
                        .addGap(44, 44, 44)
                        .addComponent(B_limpiar)
                        .addGap(67, 67, 67)
                        .addComponent(B_Salir)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(L_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(L_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(TF_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PF_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_limpiar)
                    .addComponent(B_Aceptar)
                    .addComponent(B_Salir))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_limpiarActionPerformed
        // TODO add your handling code here:
        TF_Usuario.setText(Empty);
        PF_Contraseña.setText(Empty);
        TF_Usuario.requestFocus();
    }//GEN-LAST:event_B_limpiarActionPerformed

    private void B_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_B_SalirActionPerformed

    private void B_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AceptarActionPerformed
        // TODO add your handling code here:
        //String []datos=new String[4];
        int i=0;
        try {
          conexion ob=new conexion();
          cn = ob.con();
          st=cn.createStatement();
          rs=st.executeQuery("call SP_Rol()");
          while(rs.next()){
         // datos[i]=rs.getString(1)+rs.getString(2)+rs.getString(3)+rs.getString(4);
         // System.out.println(rs.getString(1));
          
          if(TF_Usuario.getText().equals(Empty) || PF_Contraseña.getText().equals(Empty)){
                  JOptionPane.showMessageDialog(null,"Campos vacios","¿?",JOptionPane.INFORMATION_MESSAGE);
                  i=1;
                  break;
                  
          }else
          if(rs.getString(1).equals(TF_Usuario.getText()) && rs.getString(2).equals(PF_Contraseña.getText()) && rs.getString(3).equals("1")){
              
              
              JOptionPane.showMessageDialog(null,"BIENVENIDO ADMINISTRADOR ","BIENVENIDO!",JOptionPane.INFORMATION_MESSAGE);
              Administrador show = new Administrador();
             show.MostrarDatos(rs.getString(4),rs.getString(5),Integer.parseInt(rs.getString(6)),rs.getString(7));
             show.setVisible(true);
             this.dispose();
             i=1;
          }else
           if(TF_Usuario.getText().equals(rs.getString(1)) && rs.getString(2).equals(PF_Contraseña.getText()) && rs.getString(3).equals("2")){
             JOptionPane.showMessageDialog(null,"BIENVENIDO CAJERO ","BIENVENIDO!",JOptionPane.INFORMATION_MESSAGE);
             Cajero show = new Cajero();
             show.MostrarDatos(rs.getString(4),rs.getString(5),Integer.parseInt(rs.getString(6)),rs.getString(7));
             show.setVisible(true);
             this.dispose();
             i=1;
          }              
           
         // i++;
          
          }
          
          cn.close();
          st.close();
          rs.close();
          }
         catch (Exception e) {
          System.out.println("Error al extraer de la base de datos ("+e.getMessage()+")");
        }
            if(i==0)
        JOptionPane.showMessageDialog(null,"Error en el usuario o contraseña","ERROR!",JOptionPane.ERROR_MESSAGE);
            
         
         
    }//GEN-LAST:event_B_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Aceptar;
    private javax.swing.JButton B_Salir;
    private javax.swing.JButton B_limpiar;
    private javax.swing.JLabel L_Contraseña;
    private javax.swing.JLabel L_Inicio;
    private javax.swing.JLabel L_Nombre;
    private javax.swing.JPasswordField PF_Contraseña;
    private javax.swing.JTextField TF_Usuario;
    // End of variables declaration//GEN-END:variables

}
